/*
 * Generated by the Week 12 Part 2 route planner.
 */
#pragma once

struct CourseMotion {
    float turnDeg;
    float distanceMm;
};

const char PRE_COMMANDS[] = "llffrflffflflfrfl";
const char POST_COMMANDS[] = "rflfrfrflfflf";
const CourseMotion COURSE_MOTIONS[] = {
    {0.00f, 110.00f},
    {-45.00f, 424.26f},
    {45.00f, 215.00f},
    {45.00f, 35.36f},
    {-45.00f, 120.00f},
    {-45.00f, 63.64f},
    {-45.00f, 345.00f},
    {-45.00f, 134.35f},
    {45.00f, 140.00f}
};
const unsigned int COURSE_MOTION_COUNT = 9;
