/*
 * Generated by the Week 12 Part 2 route planner.
 */
#pragma once

struct CourseMotion {
    float turnDeg;
    float distanceMm;
};

const char PRE_COMMANDS[] = "llffl";
const char POST_COMMANDS[] = "frfff";
const CourseMotion COURSE_MOTIONS[] = {
    {0.00f, 170.00f},
    {-45.00f, 14.14f},
    {45.00f, 115.00f},
    {45.00f, 424.26f},
    {-45.00f, 315.00f},
    {45.00f, 98.99f},
    {-45.00f, 100.00f}
};
const unsigned int COURSE_MOTION_COUNT = 7;
