/*
 * Generated by the Week 12 Part 2 route planner.
 */
#pragma once

struct CourseMotion {
    float turnDeg;
    float distanceMm;
};

const char PRE_COMMANDS[] = "";
const char POST_COMMANDS[] = "";

const CourseMotion COURSE_MOTIONS[] = {
    {0.00f, 165.00f},
    {-45.00f, 21.21f},
    {45.00f, 120.00f},
    {45.00f, 417.19f},
    {-45.00f, 305.00f},
    {45.00f, 113.14f},
    {-45.00f, 100.00f}
};

const unsigned int COURSE_MOTION_COUNT = 7;
