/*
 * Week 12 Part 2
 *
 * COURSE_MOTIONS is generated by the planner and is left unchanged.
 * Movement control is based on the working Week 12 Part 1 controller,
 * using the requested constants below.
 */

#include <Wire.h>
#include <MPU6050_light.h>
#include "Motor.hpp"
#include "DualEncoder.hpp"
#include "Lidar.hpp"
#include "GeneratedRoute.h"

#define MOT1PWM 11
#define MOT1DIR 12
#define MOT2PWM 9
#define MOT2DIR 10
#define ENC1A 2
#define ENC1B 7
#define ENC2A 3
#define ENC2B 8

#define LEFT_LIDAR_XSHUT A0
#define RIGHT_LIDAR_XSHUT A1
#define FRONT_LIDAR_XSHUT A2
#define LEFT_LIDAR_ADDRESS 0x30
#define RIGHT_LIDAR_ADDRESS 0x31
#define FRONT_LIDAR_ADDRESS 0x32

mtrn3100::Motor motor1(MOT1PWM, MOT1DIR);
mtrn3100::Motor motor2(MOT2PWM, MOT2DIR);
mtrn3100::DualEncoder encoder(ENC1A, ENC1B, ENC2A, ENC2B);
MPU6050 mpu(Wire);
mtrn3100::Lidar leftLidar;
mtrn3100::Lidar rightLidar;
mtrn3100::Lidar frontLidar;

const float CELL_DISTANCE_M = 0.185;
const float WHEEL_RADIUS_M = 0.017;
// Run at full PWM. Steering remains possible by slowing only one wheel when
// the other wheel is already at the 255 PWM maximum.
const int FORWARD_PWM = 200;
const int MAX_FORWARD_CORRECTION = 25;
const float HEADING_KP = 2.0;

const int MAX_TURN_PWM = 150;
const int MEDIUM_TURN_PWM = 80;
const int SLOW_TURN_PWM = 50;
const float TURN_TOLERANCE = 3.0;
const float DISTANCE_TOLERANCE = 0.15;

// The IMU remains the main heading controller. When the robot is between two
// visible side walls, the side LiDARs make only a small correction toward the
// middle; the emergency nudge remains a last-resort safety correction.
const int SIDE_CENTRE_MIN_MM = 25;
const int SIDE_CENTRE_MAX_MM = 120;
const int SIDE_CENTRE_DEADBAND_MM = 12;
const int SIDE_CENTRE_CORRECTION = 4;
const int SIDE_EMERGENCY_MM = 15;
const int SIDE_EMERGENCY_CORRECTION = 5;
const int SIDE_EMERGENCY_CONFIRMATIONS = 4;
const unsigned long SIDE_NUDGE_DURATION_MS = 50;
const unsigned long SIDE_NUDGE_COOLDOWN_MS = 500;
// A forward segment is normally completed by the encoders. If a wall is
// genuinely close in front, finish only that segment and immediately continue
// to the next planned CourseMotion; do not stop the complete sequence.
const int FRONT_WALL_END_MM = 30;

const unsigned long LIDAR_UPDATE_MS = 45;

const unsigned long DRIVE_TIMEOUT = 3000;
const unsigned long TURN_TIMEOUT = 6000;
const unsigned long SETTLE_TIME = 60;
const bool PRINT_LIDAR_READINGS = false;

float targetHeading = 0.0;
bool systemReady = false;
bool sequenceFailed = false;
unsigned int motionIndex = 0;

int leftCloseCount = 0;
int rightCloseCount = 0;
int activeSideNudge = 0;
unsigned long sideNudgeEndsAt = 0;
unsigned long sideNudgeCooldownEndsAt = 0;

void stopMotors() {
    motor1.setPWM(0);
    motor2.setPWM(0);
}

float wrapAngle(float angle) {
    while (angle > 180.0) angle -= 360.0;
    while (angle < -180.0) angle += 360.0;
    return angle;
}

void setForwardPWM(int leftPWM, int rightPWM) {
    leftPWM = constrain(leftPWM, -255, 255);
    rightPWM = constrain(rightPWM, -255, 255);
    motor1.setPWM(leftPWM);
    motor2.setPWM(-rightPWM);
}

void setTurnPWM(int pwm) {
    pwm = constrain(pwm, -MAX_TURN_PWM, MAX_TURN_PWM);
    motor1.setPWM(-pwm);
    motor2.setPWM(-pwm);
}

bool initialiseLidar(mtrn3100::Lidar &lidar, uint8_t xshutPin, uint8_t address) {
    digitalWrite(xshutPin, HIGH);
    delay(20);
    return lidar.init(address);
}

bool startLidars() {
    pinMode(LEFT_LIDAR_XSHUT, OUTPUT);
    pinMode(RIGHT_LIDAR_XSHUT, OUTPUT);
    pinMode(FRONT_LIDAR_XSHUT, OUTPUT);

    digitalWrite(LEFT_LIDAR_XSHUT, LOW);
    digitalWrite(RIGHT_LIDAR_XSHUT, LOW);
    digitalWrite(FRONT_LIDAR_XSHUT, LOW);
    delay(20);

    if (!initialiseLidar(leftLidar, LEFT_LIDAR_XSHUT, LEFT_LIDAR_ADDRESS)) return false;
    if (!initialiseLidar(rightLidar, RIGHT_LIDAR_XSHUT, RIGHT_LIDAR_ADDRESS)) return false;
    if (!initialiseLidar(frontLidar, FRONT_LIDAR_XSHUT, FRONT_LIDAR_ADDRESS)) return false;

    return true;
}

int readLidarMM(mtrn3100::Lidar &lidar) {
    uint16_t distance = lidar.readDistance();
    if (!lidar.isLastReadValid()) return -1;
    return distance;
}

int calculateLidarCorrection(int leftMM, int rightMM) {
    const bool leftValid = leftMM >= 0;
    const bool rightValid = rightMM >= 0;

    if (leftValid && rightValid &&
        leftMM >= SIDE_CENTRE_MIN_MM && leftMM <= SIDE_CENTRE_MAX_MM &&
        rightMM >= SIDE_CENTRE_MIN_MM && rightMM <= SIDE_CENTRE_MAX_MM) {
        int sideError = leftMM - rightMM;
        if (abs(sideError) > SIDE_CENTRE_DEADBAND_MM) {
            return constrain(
                sideError / 6,
                -SIDE_CENTRE_CORRECTION,
                SIDE_CENTRE_CORRECTION
            );
        }
    }

    if ((long)(millis() - sideNudgeCooldownEndsAt) < 0) return 0;

    const bool leftClose = leftValid && leftMM <= SIDE_EMERGENCY_MM;
    const bool rightClose = rightValid && rightMM <= SIDE_EMERGENCY_MM;
    leftCloseCount = leftClose ? leftCloseCount + 1 : 0;
    rightCloseCount = rightClose ? rightCloseCount + 1 : 0;

    const bool leftConfirmed = leftCloseCount >= SIDE_EMERGENCY_CONFIRMATIONS;
    const bool rightConfirmed = rightCloseCount >= SIDE_EMERGENCY_CONFIRMATIONS;

    if (leftConfirmed && rightConfirmed) {
        if (leftMM > rightMM) activeSideNudge = SIDE_EMERGENCY_CORRECTION;
        else if (rightMM > leftMM) activeSideNudge = -SIDE_EMERGENCY_CORRECTION;
    } else if (leftConfirmed) {
        activeSideNudge = -SIDE_EMERGENCY_CORRECTION;
    } else if (rightConfirmed) {
        activeSideNudge = SIDE_EMERGENCY_CORRECTION;
    }

    if (activeSideNudge != 0) {
        sideNudgeEndsAt = millis() + SIDE_NUDGE_DURATION_MS;
        leftCloseCount = 0;
        rightCloseCount = 0;
        return activeSideNudge;
    }

    return 0;
}

bool turnToHeading(float newHeading) {
    targetHeading = wrapAngle(newHeading);
    unsigned long startTime = millis();
    unsigned long settledSince = 0;

    while (millis() - startTime < TURN_TIMEOUT) {
        mpu.update();
        float error = wrapAngle(targetHeading - mpu.getAngleZ());

        if (fabs(error) <= TURN_TOLERANCE) {
            stopMotors();
            if (settledSince == 0) settledSince = millis();
            if (millis() - settledSince >= SETTLE_TIME) {
                Serial.print("Turn complete. Heading = ");
                Serial.println(mpu.getAngleZ());
                return true;
            }
        } else {
            settledSince = 0;
            int turnPWM;
            if (fabs(error) > 35.0) turnPWM = MAX_TURN_PWM;
            else if (fabs(error) > 15.0) turnPWM = MEDIUM_TURN_PWM;
            else turnPWM = SLOW_TURN_PWM;

            if (error < 0) turnPWM = -turnPWM;
            setTurnPWM(turnPWM);
        }

        delay(10);
    }

    stopMotors();
    Serial.println("Turn timeout");
    return false;
}

bool turnRelative(float deltaDeg) {
    return turnToHeading(targetHeading + deltaDeg);
}

bool driveCourseDistance(float distanceMm) {
    const float targetDistanceM = distanceMm / 1000.0;
    const float targetRotation = targetDistanceM / WHEEL_RADIUS_M;

    const float leftStart = encoder.getLeftRotation();
    const float rightStart = -encoder.getRightRotation();

    unsigned long startTime = millis();
    unsigned long lastLidarUpdate = 0;
    int lidarCorrection = 0;
    int frontMM = -1;

    // Reset side-wall correction state for every planner segment.
    leftCloseCount = 0;
    rightCloseCount = 0;
    activeSideNudge = 0;
    sideNudgeEndsAt = 0;
    sideNudgeCooldownEndsAt = 0;

    while (millis() - startTime < DRIVE_TIMEOUT) {
        mpu.update();

        if (activeSideNudge != 0 &&
            (long)(millis() - sideNudgeEndsAt) >= 0) {
            activeSideNudge = 0;
            lidarCorrection = 0;
            sideNudgeCooldownEndsAt = millis() + SIDE_NUDGE_COOLDOWN_MS;
        }

        if (millis() - lastLidarUpdate >= LIDAR_UPDATE_MS) {
            int leftMM = readLidarMM(leftLidar);
            int rightMM = readLidarMM(rightLidar);
            frontMM = readLidarMM(frontLidar);
            lidarCorrection = calculateLidarCorrection(leftMM, rightMM);
            lastLidarUpdate = millis();

            if (PRINT_LIDAR_READINGS) {
                Serial.print("L: "); Serial.print(leftMM);
                Serial.print(" R: "); Serial.print(rightMM);
                Serial.print(" F: "); Serial.print(frontMM);
                Serial.print(" side correction: "); Serial.println(lidarCorrection);
            }
        }

        // Use the magnitude travelled by each wheel during THIS segment.
        // This prevents signed encoder deltas from cancelling after turns.
        const float leftTravel = fabs(encoder.getLeftRotation() - leftStart);
        const float rightTravel = fabs((-encoder.getRightRotation()) - rightStart);
        const float averageTravel = (leftTravel + rightTravel) / 2.0;

        const float headingError = wrapAngle(targetHeading - mpu.getAngleZ());
        const int imuCorrection = constrain(
            (int)(HEADING_KP * headingError),
            -MAX_FORWARD_CORRECTION,
            MAX_FORWARD_CORRECTION
        );
        const int totalCorrection = constrain(
            imuCorrection + lidarCorrection,
            -MAX_FORWARD_CORRECTION,
            MAX_FORWARD_CORRECTION
        );

        if (frontMM >= 0 && frontMM <= FRONT_WALL_END_MM) {
            stopMotors();
            Serial.print("Front wall detected at ");
            Serial.print(frontMM);
            Serial.println(" mm; continuing to next CourseMotion");
            return true;
        }

        if (averageTravel >= targetRotation - DISTANCE_TOLERANCE) {
            stopMotors();
            Serial.print("Forward complete: ");
            Serial.print(distanceMm);
            Serial.println(" mm");
            return true;
        }

        int leftPWM = FORWARD_PWM;
        int rightPWM = FORWARD_PWM;

        // Same steering strategy as the working Part 1 controller:
        // keep one wheel at PWM 200 and slow only the inside wheel.
        if (totalCorrection > 0) {
            leftPWM -= 2 * totalCorrection;
        } else if (totalCorrection < 0) {
            rightPWM += 2 * totalCorrection;
        }

        setForwardPWM(leftPWM, rightPWM);
        delay(5);
    }

    stopMotors();
    Serial.println("Forward timeout");
    return false;
}

void setup() {
    Serial.begin(115200);
    Wire.begin();
    stopMotors();
    delay(1000);

    if (!startLidars()) {
        Serial.println("Lidar initialisation failed");
        return;
    }

    byte imuStatus = mpu.begin();
    if (imuStatus != 0) {
        Serial.println("IMU connection failed");
        return;
    }

    Serial.println("Keep robot completely still during calibration");
    delay(1000);
    mpu.calcOffsets(true, true);
    delay(500);
    mpu.update();
    targetHeading = mpu.getAngleZ();

    Serial.print("Initial heading = ");
    Serial.println(targetHeading);
    Serial.println("Course controller ready");

    delay(2000);
    systemReady = true;
}

void loop() {
    if (!systemReady || sequenceFailed) {
        stopMotors();
        return;
    }

    if (motionIndex >= COURSE_MOTION_COUNT) {
        stopMotors();
        return;
    }

    const CourseMotion &motion = COURSE_MOTIONS[motionIndex];

    Serial.print("Motion ");
    Serial.print(motionIndex + 1);
    Serial.print("/");
    Serial.print(COURSE_MOTION_COUNT);
    Serial.print(": turn ");
    Serial.print(motion.turnDeg);
    Serial.print(" deg, drive ");
    Serial.print(motion.distanceMm);
    Serial.println(" mm");

    bool success = true;

    if (fabs(motion.turnDeg) > 0.1) {
        success = turnRelative(motion.turnDeg);
    }

    stopMotors();
    delay(SETTLE_TIME);

    if (success && motion.distanceMm > 0.1) {
        success = driveCourseDistance(motion.distanceMm);
    }

    stopMotors();

    if (!success) {
        sequenceFailed = true;
        Serial.println("Sequence stopped");
        return;
    }

    motionIndex++;
    delay(SETTLE_TIME);

    if (motionIndex >= COURSE_MOTION_COUNT) {
        Serial.println("All COURSE_MOTIONS completed");
    }
}
