/*
 * Generated by the Week 12 Part 2 route planner.
 */
#pragma once

const char PRE_COMMANDS[] = "rfffr";
const char COURSE_COMMANDS[] = "fffrffff";
const char POST_COMMANDS[] = "lfrflflfrfrflflfrflflff";
